version: "3.9"
services:
  web:
    build: ./backend
    volumes:
      - ./backend:/appdata/
    environment:
      - JWT_SECRET_KEY='t1NP63m4wnBg6nyHYKfmc2TpCOGI4nss'
  nginx:
    build: ./nginx
    volumes: 
      - ./nginx/nginxdata:/var/log/nginx
    container_name: webserver
    ports:
        - 8001:8001
    restart: on-failure
    
  exporter:
    image: nginx/nginx-prometheus-exporter:0.2.0
    container_name: nginx-exporter1
    restart: on-failure
   
    # volumes:
    #   - ./data:/etc/prometheus/
    #   - ./data/:/prometheus
    environment: 
      - SCRAPE_URI=http://webserver:8001/metrics
      - NGINX_RETRIES=10
      - TELEMETRY_PATH=/prometheus
      - SSL_VERIFY=false
    # command:
    #   - '-config.file=/etc/prometheus/prometheus.yml'
    #   - '-storage.tsdb.path=/prometheus'
      # - '--web.listen-address="localhost:8001'
    expose:
      - 9113
    ports:
      - 9113:9113
    links:
      - nginx:nginx
    
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./data:/etc/prometheus/
      - ./data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      # - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - exporter:exporter
     
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    # links:
    #   - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=true
    
      # - GF_SMTP_HOST=smtp.gmail.com:587
      # - GF_SMTP_USER=myadrress@gmail.com
      # - GF_SMTP_PASSWORD=mypassword
      # - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
    ports:
      - 3000:3000
  loki:
    image: grafana/loki:master-2739551
    ports:
      - "3100:3100"
    restart: unless-stopped

  promtail-nginx:
    image: grafana/promtail:master-2739551
    volumes:
      - ./data/promtail-nginx.yml:/etc/promtail/promtail.yml
      - ./nginx/nginxdata:/var/log/nginx
    command:
      - '-config.file=/etc/promtail/promtail.yml'
    restart: unless-stopped






  